name: faketooth
description: The Faketooth Flutter Plugin allows you to emulate a Bluetooth Low 
  Energy (BLE) device on iOS, macOS, watchOS, and tvOS targets from within your 
  Flutter applications
version: 0.1.2
homepage: https://github.com/rozd/faketooth-flutter

environment:
  sdk: '>=2.14.3 <4.0.0'
  flutter: ">=2.5.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FaketoothPlugin
